#include <stdio.h>
#include "errors.h"

char* errors[] = 
{
	OK,
	MSG_ERROR_NULL_POINTER,
	MSG_ERROR_NO_MEMORY,
	MSG_ERROR_NO_DISK_MEMORY,
	MSG_ERROR_OPENING_FILE,
	MSG_ERROR_INVALID_INVOCATION,
	MSG_ERROR_INVALID_INVOCATION_FMT,
	MSG_ERROR_INVALID_INVOCATION_SORT_MODE,
	MSG_ERROR_NO_COMPARATOR_SETTED,	
	MSG_ERROR_NO_PRINTER_SETTED,
	MSG_ERROR_NO_CONTEXT_SETTED,
	MSG_ERROR_NO_HEADER_SETTED,
	MSG_ERROR_NO_FOOTER_SETTED
};

status_t show_error(status_t st)
{
	fprintf(stderr,"%s%s\n",MSG_ERROR_PREFIX, errors[st]);
	return OK;
}
